Link scripts as well

diff --git a/linkall b/linkall
--- a/linkall
+++ b/linkall
@@ -6,19 +6,19 @@ me=`basename $0`
 # Get options.
 LNOPTS=""
 if [ $# -gt 0 ]; then
-	if [[ "$1" == "-f" ]]; then
-		LNOPTS="-f"
-	else
-		echo "Unrecognized option: $1"
-		cat << EOF
+  if [[ "$1" == "-f" ]]; then
+    LNOPTS="-f"
+  else
+    echo "Unrecognized option: $1"
+    cat << EOF
 Usage: $me [OPTIONS]
 
     Options:
     -f    Force 'ln' to create a new link, even if one already exists with the
           same name.
 EOF
-		exit 1
-	fi
+    exit 1
+  fi
 fi
 
 # The system name is used to link platform-specific files.
@@ -29,6 +29,7 @@ platform=`uname`
 # Lifted from http://stackoverflow.com/a/4774063
 pushd `dirname $0` > /dev/null
 SCRIPTPATH=`pwd`
+BINPATH="$SCRIPTPATH/bin"
 SCRIPTPATH="$SCRIPTPATH/configs"
 popd > /dev/null
 
@@ -38,29 +39,65 @@ echo "Creating symlinks for all configuration files in $SCRIPTPATH."
 echo ""
 
 for dotfile in `find $SCRIPTPATH -mindepth 1 -maxdepth 1`; do
-	if [[ "${dotfile##*/}" == "bashrc" ]]; then
-		linkfile=".bash_profile"
-	else
-		# If the dotfile starts with an underscore-braced string, only link it if 
-		# that string matches our platform.
-		if [[ "${dotfile##*/}" =~ "_.*_" ]]; then
-			if [[ "${dotfile##*/}" =~ "_${platform}_" ]]; then
-				linkfile=".${dotfile##*/_${platform}_}"
-			else
-				continue
-			fi
-		else
-			# This is the common case. Link the base name.
-			linkfile=".${dotfile##*/}"
-		fi
-	fi
+  if [[ "${dotfile##*/}" == "bashrc" ]]; then
+    linkfile=".bash_profile"
+  else
+    # If the dotfile starts with an underscore-braced string, only link it if 
+    # that string matches our platform.
+    if [[ "${dotfile##*/}" =~ "_.*_" ]]; then
+      if [[ "${dotfile##*/}" =~ "_${platform}_" ]]; then
+        linkfile=".${dotfile##*/_${platform}_}"
+      else
+        continue
+      fi
+    else
+      # This is the common case. Link the base name.
+      linkfile=".${dotfile##*/}"
+    fi
+  fi
 
-	echo -n "Linking $dotfile -> $linkfile... "
-	ln -s $LNOPTS "$dotfile" "$linkfile" > /dev/null 2>&1
-	if [ $? -eq 0 ]; then
-		echo "OK"
-	else
-		echo "Failed"
-	fi
+  echo -n "Linking $dotfile -> $linkfile... "
+  ln -s $LNOPTS "$dotfile" "$linkfile" > /dev/null 2>&1
+  if [ $? -eq 0 ]; then
+    echo "OK"
+  else
+    if [ -f "$linkfile" ]; then
+      echo "Exists"
+    else
+      echo "Failed"
+    fi
+  fi
 done
+
+if [ ! -d "$HOME/bin" ]; then
+  echo "Creating ~/bin directory."
+  mkdir "$HOME/bin"
+fi
+
+# Return to original pwd.
+popd > /dev/null
+
+# Move into bin dir.
+pushd "$HOME/bin" > /dev/null
+
+echo ""
+echo "Creating symlinks for executable scripts in $BINPATH."
+echo ""
+
+for script in `find $BINPATH -mindepth 1 -maxdepth 1`; do
+  linkfile="${script##*/}"
+  echo -n "Linking $dotfile -> $linkfile... "
+  ln -s $LNOPTS "$script" "$linkfile" > /dev/null 2>&1
+  if [ $? -eq 0 ]; then
+    echo "OK"
+  else
+    if [ -f "$linkfile" ]; then
+      echo "Exists"
+    else
+      echo "Failed"
+    fi
+  fi
+done
+
+# Return to original pwd.
 popd > /dev/null
